authors/urls.py
from django.urls import path

from . import views

app_name = "authors"
urlpatterns = [
    path("", views.list, name="list"),
    path("<int:author_id>/", views.details, name="details")
]

books/urls.py
from django.urls import path

from . import views

app_name = "books"
urlpatterns = [
    path("", views.list, name="list"),
    path("<int:book_id>/", views.details, name="details")
]

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("users.urls"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = "posts"
urlpatterns = [
    path("", views.listview, name="list"),
    path("<int:post_id>", views.details, name="details")
]

users/urls.py
from django.urls import path

from users.views import dashboard, example_view

urlpatterns = [
    path("", dashboard, name='dashboard'),
    path("examples/formform", example_view, name='example_form')
]

authors/models.py
from django.db import models

# Create your models here.



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='auhtors', null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Bio(models.Model):
    author = models.OneToOneField('authors.Author', on_delete=models.CASCADE)
    bio = models.TextField()

books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    author = models.ForeignKey('authors.Author', on_delete=models.CASCADE, related_name="books")
    tags = models.ManyToManyField("tags.Tag")

    def __str__(self):
        return f"{self.title} ({self.author})"

    def a_first_name(self):
        return self.author.first_name

comments/models.py
from django.db import models

# Create your models here.


class CommentPost(models.Model):
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("posts.Post", on_delete=models.CASCADE, related_name="comments")

galleries/models.py
from django.db import models

# Create your models here.


class Gallery(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Photo(models.Model):
    image = models.ImageField(upload_to='galleries/')
    description = models.TextField()
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self): return self.title

tags/models.py
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

comments/forms.py
from django import forms

from comments.models import CommentPost


class CommentForm(forms.Form):
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)


class CommentForm2(forms.ModelForm):

    class Meta:
        model = CommentPost
        exclude = ["post"]

posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)


class PostForm2(forms.ModelForm):

    class Meta:
        model = Post
        fields = ["title", 'content',]

users/forms.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField()
    email = forms.EmailField()

    def clean_email(self):
        if self.cleaned_data["email"] != "rkorzen@wp.pl":
            raise forms.ValidationError("Wrong email")

authors/views.py
from django.shortcuts import render

# Create your views here.
from authors.models import Author


def list(request):
    authors = Author.objects.all()
    return render(
        request,
        "authors/list.html",
        {"authors": authors}
    )



def details(request, author_id):
    author = Author.objects.get(pk=author_id)
    return render(
        request,
        "authors/details.html",
        {"author": author}
    )

books/views.py
from django.shortcuts import render

from books.models import Book


def list(request):
    books = Book.objects.all()
    return render(
        request,
        "books/list.html",
        {"books": books}
    )


def details(request, book_id):
    book = Book.objects.get(pk=book_id)

    return render(
        request,
        "books/details.html",
        {"book": book}
    )

galleries/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render
from comments.forms import CommentForm, CommentForm2

# Create your views here.
from comments.models import CommentPost
from posts.forms import PostForm, PostForm2
from posts.models import Post


def listview(request):
    posts = Post.objects.all()

    if request.method == "POST":
        form = PostForm2(data=request.POST)

        # title = request.POST.get("title")
        # content = request.POST.get("content")
        # print(request.user)
        # print(type(request.user))
        # post = Post.objects.create(
        #     title=title,
        #     content=content,
        #     author=request.user
        # )

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

    return render(
        request,
        "posts/list.html",
        {"posts": posts, 'post_form': PostForm2()}
    )


def details(request, post_id):
    post = Post.objects.get(pk=post_id)

    if request.method == "POST":
        print(request.POST)
        if 'post_submit' in request.POST:
            post_form = PostForm2(request.POST, instance=post)
            if post_form.is_valid():
                # post.title = post_form.cleaned_data['title']
                # post.content = post_form.cleaned_data['content']
                # post.save()
                post_form.save()

        elif 'comment_submit' in request.POST:
            comment_form = CommentForm2(request.POST)
            if comment_form.is_valid():
                # data = dict(comment_form.cleaned_data)
                # data['post'] = post
                # comment = CommentPost.objects.create(**data)
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.save()

    data = {'title': post.title, "content": post.content}
    post_form = PostForm2(data=data)
    comment_form = CommentForm2()

    return render(
        request,
        "posts/details.html",
        {"post": post, 'comment_form': comment_form, 'post_form': post_form}
    )

tags/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.
from users.forms import NameForm


def dashboard(request):
    return render(request, "base.html")


def example_view(request):

    if request.method == "POST":
        form = NameForm(data=request.POST)

        print(form.data)


    form = NameForm()

    return render(
        request,
        "users/example.html",
        {"form": form}
    )

templates/authors/details.html
{% extends "base.html" %}

{% block content %}
<h1>{{ author }}</h1>
  <div class="row">
    <div class="col-lg-6">
        <ul>
        {% for book in author.books.all %}
        <li><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-lg-6">
      <img src="{{ author.image.url }}" width="100%">
    </div>

  </div>
<h2>Publikacje xxx</h2>



<a href="{% url 'authors:list' %}">Lista autorów</a>
{% endblock %}

templates/authors/list.html
{% extends "base.html" %}

{% block content %}
<h1>Autorzy</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} {% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">


</head>


<body>
<div class="container">
{% include 'includes/header.html' %}
{% block content %}
Welcome ...

{% endblock %}
</div>

  <!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/books/details.html
{% extends "base.html" %}

{% block content %}
<h1></h1>

<a href="{% url 'books:list' %}">Lista książek</a>
{% endblock %}

templates/books/list.html
{% extends "base.html" %}

{% block content %}
<h1>Książki</h1>
{% endblock %}

templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
      <img src="{% static 'img/logo.jpg' %}" alt="Logo" height="50px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:list' %}">Books</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="{% url 'authors:list' %}">Authors</a>
        </li>

      </ul>3
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      {% else %}
      <a class="nav-link" href="{% url 'login' %}">Login</a>
      {% endif %}

      <form class="d-flex">
        <input class="form-control me-2" type="text" placeholder="Search">
        <button class="btn btn-primary" type="button">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/posts/details.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <small>By: {{ post.author }}</small>
  <p>{{ post.content }}</p>

  <div>
    {% for c in post.comments.all %}
      <div>
      {{ c.content }}
      <br>
      <small>{{ c.email }} | {{ c.created }}</small>
      </div>
    {% endfor %}
  </div>


  {% if user == post.author %}
    {% include 'posts/includes/post_form.html' %}
  {% endif %}

  {% include 'posts/includes/comment_form.html' %}
{% endblock %}

templates/posts/includes/comment_form.html
{% load crispy_forms_tags %}

<form method="POST">
  {% csrf_token %}
  {{ comment_form|crispy }}
  <input type="submit" value="send" name="comment_submit">
</form>

templates/posts/includes/post_form.html
{% load crispy_forms_tags %}

<form method="POST">
  {% csrf_token %}
  {{ post_form|crispy }}
  <input type="submit" value="send" name="post_submit">
</form>

templates/posts/list.html
{% extends "base.html" %}

{% block content %}
<h1>Posty</h1>

<ul>
{% for p in posts %}
  <li><a href="{% url 'posts:details' p.id %}">{{ p }}</a> </li>
{% endfor %}
</ul>
{% if user.is_authenticated %}
{% include 'posts/includes/post_form.html' %}
{% endif %}
{% endblock %}

templates/users/example.html
{% extends 'base.html' %}

{% block content %}

  <form method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
   <input type="submit" value="Send">


  </form>

{% endblock %}